const treinos=[{titulo:"TFM Iniciante - 30 dias",nivel:"iniciante",progresso:35,desc:"Para quem está começando e precisa criar base física com segurança.",itens:["Caminhada/corrida leve 20 min","3x10 flexões adaptadas","3x15 abdominais","Alongamento e mobilidade"]},{titulo:"Corrida Militar",nivel:"intermediario",progresso:55,desc:"Plano para melhorar resistência e ritmo de corrida.",itens:["2 dias de corrida leve","1 dia de tiro curto","1 dia de caminhada forte","Teste de 12 minutos"]},{titulo:"Flexão e Abdominal",nivel:"intermediario",progresso:62,desc:"Treino para melhorar força básica exigida em testes físicos.",itens:["4 séries de flexão","4 séries de abdominal","Prancha 3x30s","Descanso controlado"]},{titulo:"Barra Fixa",nivel:"avancado",progresso:45,desc:"Progressão para desenvolver costas, braços e pegada.",itens:["Suspensão na barra","Remada invertida","Negativas controladas","Barra assistida"]},{titulo:"Marcha e Resistência",nivel:"avancado",progresso:50,desc:"Preparação para resistência física e mental.",itens:["Caminhada longa","Postura corporal","Respiração","Hidratação"]},{titulo:"Mobilidade e Prevenção",nivel:"iniciante",progresso:80,desc:"Parte essencial para evitar lesões e manter evolução.",itens:["Alongamento dinâmico","Mobilidade de quadril","Tornozelo e joelho","Relaxamento"]}];

const cancoes=[{titulo:"Fibra de Herói",tipo:"Canção tradicional",desc:"Canção conhecida no meio militar, usada para motivação e espírito de corpo."},{titulo:"Canção do Exército",tipo:"Institucional",desc:"Representa tradição, patriotismo e valores do Exército Brasileiro."},{titulo:"Canção da Infantaria",tipo:"Arma base",desc:"Ligada à coragem, resistência e espírito combatente."},{titulo:"Canção da Cavalaria",tipo:"Tradição",desc:"Valoriza mobilidade, bravura e história da Cavalaria."},{titulo:"Canção da Artilharia",tipo:"Tradição",desc:"Associada à força, apoio de fogo e precisão."},{titulo:"Hino Nacional",tipo:"Cívico",desc:"Base cívica importante para qualquer cidadão e futuro militar."}];

function atualizarRelogio(){document.getElementById("clock").textContent=new Date().toLocaleString("pt-BR",{weekday:"short",hour:"2-digit",minute:"2-digit",second:"2-digit"})}
setInterval(atualizarRelogio,1000);atualizarRelogio();

function montarTreinos(lista=treinos){document.getElementById("treinoGrid").innerHTML=lista.map(t=>`<article class="card"><div class="card-top"><h3>${t.titulo}</h3><span class="badge">${t.nivel}</span></div><p>${t.desc}</p><ul class="list">${t.itens.map(i=>`<li>✅ ${i}</li>`).join("")}</ul><div class="bar"><span style="width:${t.progresso}%"></span></div></article>`).join("")}

function filtrarTreino(nivel,botao){document.querySelectorAll(".filter").forEach(b=>b.classList.remove("active"));botao.classList.add("active");montarTreinos(nivel==="todos"?treinos:treinos.filter(t=>t.nivel===nivel))}

function montarCancoes(){document.getElementById("songGrid").innerHTML=cancoes.map(c=>`<article class="song"><span class="badge">${c.tipo}</span><h3>🎵 ${c.titulo}</h3><p>${c.desc}</p><button class="btn primary" onclick="alert('Aqui você pode colocar letra, áudio ou vídeo da canção: ${c.titulo}')">Abrir canção</button></article>`).join("")}

montarTreinos();montarCancoes();